name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false
          lfs: false

      # (Optional) set Node version; SWA action will install deps automatically
      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          # 🔑 Provided via repo Settings → Secrets and variables → Actions
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_COAST_0CAFF3A1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # enables PR comments, etc.
          action: "upload"

          # App config — adjust only if your app lives elsewhere
          app_location: "/"          # Vite app at repo root
          api_location: ""           # No SWA API (backend is App Service)
          output_location: "dist"    # Vite build output

          # (Optional) force build commands; SWA usually detects package.json and runs build
          app_build_command: "npm ci && npm run build"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_COAST_0CAFF3A1E }}
          action: "close"
